### ISSUE TITLE
--dir default path

### ISSUE THREAD

**Issue by loadi** [jvstme/drope#2]
Default path for _--dir_ in _--help_ looks like it should be an absolute path:
`parser.add_argument(
    "-d",
    "--dir",
    type=Path,
    default=Path("."),
    help="save uploads here (default: %(default)s)",
)`
But I got this:
` -d DIR, --dir DIR     save uploads here (default: .)`
Is it a bug?

**Comment by jvstme** [comment]
Hi! I think this is intended behavior.
The default is to save files in the current directory (`.`). If we were to display absolute path in `--help` output, then the output would depend on the current dir. Since I want the output to be the same all the time, I believe displaying `default: .` is a better option.
